//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class classes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classes()
        {
            this.classes_member = new HashSet<classes_member>();
        }

        [DisplayName("班級編號")]
        public int class_id { get; set; }
        [DisplayName("老師帳號")]
        public string teacher_id { get; set; }
        [DisplayName("班級名稱")]
        public string class_name { get; set; }
        [DisplayName("是否可見")]
        public bool visible { get; set; }
        [DisplayName("開班時間")]
        public System.DateTime datetime { get; set; }
        [DisplayName("班級代碼")]
        public string class_code { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classes_member> classes_member { get; set; }
    }
}
