//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mall_log
    {
        public string manager_id { get; set; }
        public string product_id { get; set; }
        public string product_desc { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> active { get; set; }
        public string img_path { get; set; }
        public string used_img_path { get; set; }
        public string status { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual mall mall { get; set; }
        public virtual manager manager { get; set; }
    }
}
