//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeNow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class play_record_answer
    {
        public int play_guid { get; set; }
        public string account { get; set; }
        public int select_answer { get; set; }
        public int quiz_guid { get; set; }
    
        public virtual play_record play_record { get; set; }
    }
}
